version: '3.4'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  spl_drawdown_buyer:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
       - .:/usr/src/app
    environment:
          - MODE=BUYER